FROM python:3.11-slim

# ensure /tmp writable
RUN chmod -R 777 /tmp

WORKDIR /app/ml_service
COPY requirements.txt /app/ml_service/requirements.txt
RUN pip install --no-cache-dir -r /app/ml_service/requirements.txt
COPY . /app/ml_service/
EXPOSE 8001
CMD [ "uvicorn", "ml_service.main:app", "--host", "0.0.0.0", "--port", "8001" ]
